CREATE DATABASE btech_student_tracker;
use btech_student_tracker;
create table STUDENTS(
ID INT auto_increment PRIMARY KEY,
ROLL_NO VARCHAR(30) UNIQUE NOT NULL,
NAME VARCHAR(100)NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(15),
BRANCH varchar(50) NOT NULL,
SEMESTER INT NOT NULL,
CGPA DECIMAL(3,2));

CREATE TABLE PERFORMANCE(
ID INT auto_increment PRIMARY KEY,
STUDENT_ID INT NOT NULL,
SUBJECT VARCHAR(100)NOT NULL,
MARKS DECIMAL(5,2) NOT NULL,
GRADE VARCHAR(2),

foreign key(STUDENT_ID)
references STUDENTS(ID)
ON DELETE cascade
);
USE btech_student_tracker;
SELECT * FROM STUDENTS;

USE btech_student_tracker;
SELECT * FROM PERFORMANCE;

USE btech_student_tracker;
SELECT * FROM STUDENTS;
SELECT * FROM PERFORMANCE;

USE btech_student_tracker;
SELECT
    S.ID AS STUDENT_ID,
    S.ROLL_NO,
    S.NAME,
    S.EMAIL,
    S.PHONE,
    S.BRANCH,
    S.SEMESTER,
    S.CGPA,

    GROUP_CONCAT(P.SUBJECT ORDER BY P.ID SEPARATOR ', ') AS SUBJECTS,

    GROUP_CONCAT(P.MARKS ORDER BY P.ID SEPARATOR ', ') AS MARKS,

    GROUP_CONCAT(P.GRADE ORDER BY P.ID SEPARATOR ', ') AS GRADES

FROM STUDENTS S
INNER JOIN PERFORMANCE P
    ON S.ID = P.STUDENT_ID

GROUP BY
    S.ID,
    S.ROLL_NO,
    S.NAME,
    S.EMAIL,
    S.PHONE,
    S.BRANCH,
    S.SEMESTER,
    S.CGPA;
    
    
    
    -- details of student store
  /*  USE btech_student_tracker;
SELECT
    S.ID AS STUDENT_ID,
    S.ROLL_NO,
    S.NAME,
    S.PHONE,
    S.BRANCH,
    S.SEMESTER,
    S.CGPA,
    GROUP_CONCAT(P.SUBJECT SEPARATOR ', ') AS SUBJECTS,
    GROUP_CONCAT(P.MARKS SEPARATOR ', ') AS MARKS,
    GROUP_CONCAT(P.GRADE SEPARATOR ', ') AS GRADES
FROM STUDENTS S
INNER JOIN PERFORMANCE P
    ON S.ID = P.STUDENT_ID
GROUP BY
    S.ID,
    S.ROLL_NO,
    S.NAME,
    S.PHONE,
    S.BRANCH,
    S.SEMESTER,
    S.CGPA;
    */
    USE btech_student_tracker;
UPDATE STUDENTS
SET ROLL_NO = '25462LE'
WHERE ID = 2;
    UPDATE STUDENTS
SET ROLL_NO = '25462LE'
WHERE ID = 2;
SELECT * FROM STUDENTS;



    
    